const api = require('@forge/api');
const { getConfig, validateConfig } = require('./config');
const { fetchTaskDataByKey } = require('./jiraDataFetcher');
const { fetchFigmaDesignData } = require('./figmaFetcher');
const { generateTestCases } = require('./aiGenerator');
const { attachCsvToJira } = require('./csvAttachment');
const { exportToGoogleSheets } = require('./googleSheetsExporter');

async function addJiraComment(issueKey, body) {
  try {
    const res = await api.asApp().requestJira(
      api.route`/rest/api/3/issue/${issueKey}/comment`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ body }),
      }
    );
    if (!res.ok) console.error(`[Worker] Comment failed: ${res.status}`);
  } catch (err) {
    console.error('[Worker] Comment error:', err.message);
  }
}

function makeErrorComment(text) {
  return {
    type: 'doc', version: 1,
    content: [{ type: 'paragraph', content: [{ type: 'text', text }] }],
  };
}

async function handler(event) {
  const { issueKey, trigger = 'transition' } = event.body;
  console.log(`[Worker] Processing ${issueKey} | trigger: ${trigger}`);

  // ── Bước 1: Load config ──
  let config;
  try {
    config = await getConfig();
    validateConfig(config);
  } catch (err) {
    console.error('[Worker] Config error:', err.message);
    await addJiraComment(issueKey, makeErrorComment(`⚠️ AI TestCase Generator — Config error: ${err.message}`));
    return;
  }

  // ── Bước 2: Fetch Jira task data ──
  let taskData;
  try {
    taskData = await fetchTaskDataByKey(issueKey);
  } catch (err) {
    console.error('[Worker] Jira fetch failed:', err.message);
    return;
  }
  if (!taskData) {
    console.log(`[Worker] ${issueKey} skipped (title filter)`);
    return;
  }

  const { platform, figmaLinks } = taskData;

  // ── Bước 3: Figma (optional) ──
  let figmaData = null;
  if (figmaLinks.length > 0) {
    try {
      figmaData = await fetchFigmaDesignData(figmaLinks, config);
    } catch (err) {
      console.warn('[Worker] Figma skipped:', err.message);
    }
  }

  // ── Bước 4: Generate test cases ──
  let testCases;
  try {
    testCases = await generateTestCases(taskData, figmaData, config);
  } catch (err) {
    console.error('[Worker] AI failed:', err.message);
    await addJiraComment(issueKey, makeErrorComment(`⚠️ AI TestCase Generator — AI error: ${err.message}`));
    return;
  }

  // ── Bước 5: Attach CSV ──
  let filename;
  try {
    const result = await attachCsvToJira(issueKey, platform, testCases);
    filename = result.filename;
  } catch (err) {
    console.error('[Worker] CSV attach failed:', err.message);
    await addJiraComment(issueKey, makeErrorComment(`⚠️ AI TestCase Generator — CSV attach failed: ${err.message}`));
    return;
  }

  // ── Bước 5b: Google Sheets (optional) ──
  let sheetsUrl = null;
  if (config.appsScriptUrl) {
    try {
      const issueUrl = taskData.siteUrl ? `${taskData.siteUrl}/browse/${issueKey}` : '';
      const meta = {
        issueTitle: taskData.title  || issueKey,
        issueUrl,
        assignee:   taskData.assignee || '',
      };
      const result = await exportToGoogleSheets(issueKey, platform, testCases, config, meta);
      sheetsUrl = result.url;
    } catch (err) {
      console.warn('[Worker] Sheets skipped:', err.message);
    }
  }

  // ── Bước 6: Comment kết quả (ADF format with clickable link) ──
  const platformLabel = platform === 'web' ? 'Web' : 'Mobile (Android + iOS)';

  const commentContent = [
    { type: 'paragraph', content: [
      { type: 'text', text: '🤖 Auto-Generated Test Cases', marks: [{ type: 'strong' }] },
    ]},
    { type: 'paragraph', content: [
      { type: 'text', text: `✅ ${testCases.length} test cases generated` },
    ]},
    { type: 'paragraph', content: [
      { type: 'text', text: `📋 Platform: ${platformLabel}` },
    ]},
  ];

  if (figmaData) {
    commentContent.push({ type: 'paragraph', content: [
      { type: 'text', text: `🎨 Figma: ${figmaData.screens.length} screen(s) analyzed` },
    ]});
  }

  commentContent.push({ type: 'paragraph', content: [
    { type: 'text', text: `📎 Attachment: ${filename}` },
  ]});

  if (sheetsUrl) {
    commentContent.push({ type: 'paragraph', content: [
      { type: 'text', text: '📊 Google Sheets: ' },
      { type: 'inlineCard', attrs: { url: sheetsUrl } },
    ]});
  }

  commentContent.push({ type: 'paragraph', content: [
    { type: 'text', text: 'Generated by AI TestCase Generator', marks: [{ type: 'em' }] },
  ]});

  await addJiraComment(issueKey, { type: 'doc', version: 1, content: commentContent });

  console.log(`[Worker] Done: ${issueKey} → ${testCases.length} test cases, attached ${filename}${sheetsUrl ? `, sheets: ${sheetsUrl}` : ''}`);
}

module.exports = { handler };
